Fix typos in slack integration steps
argoproj-labs/argocd-notifications pull request #269
Opened 2021-04-28 14:23 UTC by vineshkamble

2021-04-28 14:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj-labs/argocd-notifications?pullRequest=269) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj-labs/argocd-notifications?pullRequest=269) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj-labs/argocd-notifications?pullRequest=269) it.</sub>

2021-04-28 18:56 UTC, alexmt requested changes
Thank you for improving the doc @vineshkamble ! The `docs/services` is automatically copied from https://github.com/argoproj/notifications-engine/tree/master/docs/services (need to add a note about it in this repo ).

Can you please move your changes to https://github.com/argoproj/notifications-engine repo?

2021-04-28 19:44 UTC, vineshkamble commented
Sure Alex,
I'll move my changes to https://github.com/argoproj/notifications-engine
and will raise pull request again.
Please do correct me if I am wrong.

Thank you,

Vinesh Kamble




On Thu, Apr 29, 2021 at 12:26 AM Alexander Matyushentsev <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thank you for improving the doc @vineshkamble
> <https://github.com/vineshkamble> ! The docs/services is automatically
> copied from
> https://github.com/argoproj/notifications-engine/tree/master/docs/services
> (need to add a note about it in this repo ).
>
> Can you please move your changes to
> https://github.com/argoproj/notifications-engine repo?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/argoproj-labs/argocd-notifications/pull/269#pullrequestreview-647414116>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AESQCULKHBM6H77HRL7SACLTLBK6PANCNFSM43XGDCGQ>
> .
>

2021-05-01 16:17 UTC, ryota-sakamoto commented
fixed by https://github.com/argoproj/notifications-engine/pull/9

2021-05-01 16:17 UTC, closed without merging